INSERT INTO `abilita` (`Abilita`, `Potenza`, `EroeID`)
VALUES
    ('Armatura Tecnologica', 'Elevata', 1),
    ('Super Forza', 'Elevata', 2),
    ('Martello di Thor', 'Divina', 3),
    ('Spionaggio', 'Media', 4),
    ('Forza Sovrumana', 'Elevata', 5),
    ('Magia', 'Elevata', 6),
    ('Freccia Esplosiva', 'Media', 7),
    ('Guanto del Infinito', 'Divina', 8),
    ('Vibranio', 'Alta', 9),
    ('Volare', 'Elevata', 10),
    ('Forza e Agilità', 'Elevata', 11),
    ('Riduzione Dimensionale', 'Elevata', 12),
    ('Controllo delle Formiche', 'Elevata', 13),
    ('Stinger Blasts', 'Alta', 14),
    ('Telepatia', 'Bassa', 15),
    ('Telecinesi', 'Bassa', 16),
    ('Velocità Supersonica', 'Elevata', 17),
    ('Controllo delle Api', 'Bassa', 18),
    ('Arrampicata', 'Media', 19),
    ('Manipolazione della Realtà', 'Divina', 20);
